kind: Pod
apiVersion: v1
metadata:
    name: appb
    namespace: default
    uid: a8c5dba1-c6e5-41af-aa42-9d864590046c
    resourceVersion: "326717"
    creationTimestamp: 2022-10-19T12:03:23Z
    labels:
        app: appb
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"appa"},"name":"appa","namespace":"default"},"spec":{"containers":[{"image":"nginx:alpine","name":"nginx","ports":[{"containerPort":80}]}]}}
spec:
    volumes:
        - name: kube-api-access-pxq9f
          projected:
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    name: kube-root-ca.crt
                    items:
                        - key: ca.crt
                          path: ca.crt
                - downwardAPI:
                    items:
                        - path: namespace
                          fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
            defaultMode: 420
    containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: kube-api-access-pxq9f
              readOnly: true
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
    restartPolicy: Always
    terminationGracePeriodSeconds: 30
    dnsPolicy: ClusterFirst
    serviceAccountName: default
    serviceAccount: default
    nodeName: minikube
    securityContext: {}
    affinity:
        podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                        app: appa
                    matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - appb
                  topologyKey: kubernetes.io/hostname
            preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 80
                  podAffinityTerm:
                    labelSelector:
                        matchLabels:
                            app: appa
                        matchExpressions:
                            - key: app
                              operator: In
                              values:
                                - appe
                    topologyKey: kubernetes.io/hostname
                - weight: 60
                  podAffinityTerm:
                    labelSelector:
                        matchLabels:
                            app: appa
                        matchExpressions:
                            - key: app
                              operator: In
                              values:
                                - appf
                            - key: app
                              operator: In
                              values:
                                - appg
                    topologyKey: kubernetes.io/hostname
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                        app: appa
                    matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - appc
                        - key: app
                          operator: In
                          values:
                            - appd
                  topologyKey: kubernetes.io/hostname
            preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 40
                  podAffinityTerm:
                    labelSelector:
                        matchLabels:
                            app: appa
                        matchExpressions:
                            - key: app
                              operator: In
                              values:
                                - apph
                    topologyKey: kubernetes.io/hostname
    schedulerName: default-scheduler
    tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
    priority: 0
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
