kind: pod
apiVersion: v1
metadata:
    name: app_test
spec:
    containers: []
    affinity:
        podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - appb
                  topologyKey: kubernetes.io/hostname
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
#                - labelSelector:
#                    matchExpressions:
#                        - key: app
#                          operator: In
#                          values:
#                            - appc
#                            - appd
#                  topologyKey: kubernetes.io/hostname
                - labelSelector:
                    matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - appc
                            - appd
                        - key: app
                          operator: In
                          values:
                            - appe


                  topologyKey: kubernetes.io/hostname
